<a href="https://colab.research.google.com/github/2kunal6/code/blob/master/ml/check.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

a = np.array([1,2,3,4])
w = np.array([10, 11, 10, 10])
b = np.array([100, 100, 100, 100])

print(a*w + b)

[110 122 130 140]


In [0]:
import numpy as np

a = np.array([1,2,3,4])
w = 10
b= 100

print(a*w + b)

[110 120 130 140]


In [0]:
import numpy as np

f = np.array([[1, 101], [2, 202], [3, 303], [4, 404], [5, 505]])

for x in f.T:
  mean = np.mean(x)
  rang = x.max() - x.min()

  print(mean)
  print(rang)
  print(x)
  x = x - mean
  print(x)
  x = x/rang
  print(x)

print(f)

3.0
4.0
[1. 2. 3. 4. 5.]
[-2. -1.  0.  1.  2.]
[-0.5  -0.25  0.    0.25  0.5 ]
303.0
404.0
[101. 202. 303. 404. 505.]
[-202. -101.    0.  101.  202.]
[-0.5  -0.25  0.    0.25  0.5 ]
[[  1. 101.]
 [  2. 202.]
 [  3. 303.]
 [  4. 404.]
 [  5. 505.]]


In [0]:
pred = np.array([1,2,3,4])
targ = np.array([5,6,7,8])

x = (pred-targ)
print(x)
x = x**2
print(x)

[-4 -4 -4 -4]
[16 16 16 16]
